export const dummyVideos = [
  {
    id: "1",
    title: "Video 1",
    description: "Description 1",
    publishedAt: "2025-01-01",
    views: "1000",
    likes: "100",
    thumbnail: "https://via.placeholder.com/150",
    channelTitle: "Channel 1",
  },
  {
    id: "2",
    title: "Video 2",
    description: "Description 2",
    publishedAt: "2025-01-02",
    views: "2000",
    likes: "200",
    thumbnail: "https://via.placeholder.com/150",
    channelTitle: "Channel 2",
  },
  {
    id: "3",
    title: "Video 3",
    description: "Description 3",
    publishedAt: "2025-01-03",
    views: "3000",
    likes: "300",
    thumbnail: "https://via.placeholder.com/150",
    channelTitle: "Channel 3",
  },
];
